// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-realworld/internal/biz"
	"kratos-realworld/internal/conf"
	"kratos-realworld/internal/data"
	"kratos-realworld/internal/server"
	"kratos-realworld/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, db, client)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData)
	commentRepo := data.NewCommentRepo(dataData)
	tagRepo := data.NewTagRepo(dataData)
	socialUsecase := biz.NewSocialUsecase(articleRepo, commentRepo, tagRepo, logger)
	userRepo := data.NewUserRepo(dataData)
	profileRepo := data.NewProfileRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo, profileRepo, logger)
	realWorldService := service.NewRealWorldService(socialUsecase, userUsecase)
	grpcServer := server.NewGRPCServer(confServer, realWorldService, logger)
	httpServer := server.NewHTTPServer(confServer, realWorldService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
